server:
  port: 8761

spring:
  application:
    name: discoveryservice
  cloud:
    config:
      uri: http://localhost:8888
      name: ecommerce

eureka:
  client:
    register-with-eureka: false   # default는 true, true로 할 경우 자기자신을 등록하게 됨
    fetch-registry: false         # default는 true
